[package]
name = "caffeinate"
version = "0.1.3"
edition = "2024"

[[bin]]
name = "caffeinate"
path = "./src/main.rs"

[dependencies]
zbus = { version = "5.18", features = ["blocking-api"] }
anyhow = "1.0.104"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
pipewire-native = "0.1.4"

[profile.dist]
inherits = "release"
lto = "thin"
strip = true

[profile.dev]
opt-level = 0
debug = true
